### ISSUE TITLE
Sound Card loopback test: no measurement result

### ISSUE THREAD

**Issue by ariendj** [mincequi/qLouder#3]
![Screenshot_20221004_124601](https://user-images.githubusercontent.com/2234673/193800298-2f3c8fec-1669-4166-8fb2-fd1e011f90f5.png)
![Screenshot_20221004_124236](https://user-images.githubusercontent.com/2234673/193800127-c2751f97-b863-4f10-a774-307b02bf0f96.png)

Hello mincequi! I got qLouder to build and run :)
First thing I did is to try a loopback measurement of my sound card.
I selected the correct pipewire (PulseAudio compatibility-) devices and qpwgraph shows the audio input and output being routed to the correct devices. Volume is on full bast. Yet, after clicking on "measure" and seeing the animation, nothing happens.
The input and output devices are set to 48k, my pipewire setup is running at 192kHz 32bit floating point though. I wasn't able to specify bit depth.

Please let me know if you need more info or if there's anything I can try to assist with this :)

**Comment by mincequi** [comment]
Hi @ariendj 
nice to hear, that it is working. At least to the point where you start measuring...
To be honest: i did not have those intermediate audio frameworks (like PulseAudio, Jack, Pipewire, etc) in mind. Instead, i tried to work as direct with the hardware as possible (ALSA). Also the sample rate detection of sound cards on linux does not seem to work properly. So, i limited this tool to 44.1 and 48 kHz.
Internally, this tool works with 32bit float per default.

You could try to find the proper ALSA devices and try a lower sample rate. Your card should work with 48kHz, i assume. Btw: what is your actual sound card?

However, i need to rework the playback/recording part anyway, because i am using two different frameworks: QtMultimedia and cinder. I will port away from QtMultimedia in favor of cinder (or maybe something else).
In the meanwhile, i will also strick my nose into pipewire...

**Comment by ariendj** [comment]
My mistake. I just blindly assumed that qLouder would support JACK because that's what qLoud used (and Pipewire supports). I'll try again with the ALSA interfaces that are also listed. The dmix ones might work, unless pipewire claims full hardware access.

The soundcard I used is the Asus Xonar U7, a semi-decent USB card that should have a signal to noise ratio above 100dB in loopback mode. Mine does, at least on the left channel. Right input seems broken at under 80dB...

Thanks a lot for your help, I really appreciate you diving head first into ~~the pits of hell~~ linux desktop audio.

**Comment by mincequi** [comment]
Hey @ariendj ,
i ported away from cinder using miniaudio as playback backend in this branch. I guess, it will make it into main very soon. If you want, you can checkout this branch: https://github.com/mincequi/qLouder/tree/miniaudio

**Comment by mincequi** [comment]
Closed as ported away from cinder.

**Comment by ariendj** [comment]
I did a "git pull / make clean / cmake .. / make" and now all I get is this:
``arien@NBADJ01:~/source/qLouder/build$ ./qLouder
QML debugging is enabled. Only use this in a safe environment.
Segmentation fault
``

**Comment by mincequi** [comment]
This does not tell me much. A backtrace would be great. However, i assume it is because you use jack...
Pulseaudio should do the trick

**Comment by mincequi** [comment]
You can check latest master. This could fix your issue.
